version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: dev-db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: dev-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - my-network

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - my-network

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - postgres

    evaluation-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: evaluation-api
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        environment:
            POSTGRES_URL: postgres://user:password@postgres:5432/dev-db
            NODE_ENV: development
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./src:/app/src:ro
        networks:
            - my-network

volumes:
    postgres-data:

networks:
    my-network:
