version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: test-db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: test-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        networks:
            - network
    redis:
        image: redis:latest
        container_name: test-redis
        ports:
            - '6379:6379'
        networks:
            - network

    pgadmin:
        image: dpage/pgadmin4
        container_name: test-pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - postgres
        networks:
            - network

    evaluation-test-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: evaluation-test-api
        ports:
            - '3000:3000'
        depends_on:
            - postgres
            - redis
        environment:
            POSTGRES_URL: postgres://user:password@postgres:5432/test-db
            NODE_ENV: test
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./src:/app/src:ro
        networks:
            - network

volumes:
    postgres-data:

networks:
    network:
