version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: dev-db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: dev-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data # Persist PostgreSQL data
        networks:
            - my-network

    evaluation-api:
        build:
            context: .
            dockerfile: Dockerfile # Path to your Dockerfile for the Express app
        container_name: evaluation-api
        command: sh -c "yarn prisma:migrate && yarn dev"
        ports:
            - '3000:3000' # Map container port 3000 to host port 3000
        depends_on:
            - postgres # Wait for PostgreSQL to be ready before starting Express
        environment:
            POSTGRES_URL: postgres://user:password@postgres:5432/dev-db
            NODE_ENV: development
        volumes:
            - ./src:/app/src:ro
        networks:
            - my-network

volumes:
    postgres-data:

networks:
    my-network:
