version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: dev-db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: dev-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - dev-server

    redis:
        image: redis:latest
        container_name: dev-redis
        ports:
            - '6379:6379'
        networks:
            - dev-server

    pgadmin:
        image: dpage/pgadmin4
        container_name: dev-pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - postgres
        networks:
            - dev-server
        logging:
            driver: 'none'

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - dev-server
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        logging:
            driver: 'none'

    evaluation-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: evaluation-api
        ports:
            - '3000:3000'
        depends_on:
            - postgres
            - redis
            - elasticsearch

        environment:
            POSTGRES_URL: postgres://user:password@postgres:5432/dev-db
            NODE_ENV: development
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./src:/app/src:ro
        networks:
            - dev-server

volumes:
    postgres-data:
    elasticsearch_data:
        driver: local

networks:
    dev-server:
